id: Git_Integration-Test
version: -1
name: Git_Integration-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5a19e81d-5266-4347-8e00-581c66b43451
    type: start
    task:
      id: 5a19e81d-5266-4347-8e00-581c66b43451
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: d33efdd3-de84-4621-8e96-2f64da7b5895
    type: regular
    task:
      id: d33efdd3-de84-4621-8e96-2f64da7b5895
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "12"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: e448e079-55cd-4dd3-8a00-669e5bad3bab
    type: regular
    task:
      id: e448e079-55cd-4dd3-8a00-669e5bad3bab
      version: -1
      name: GitHub-create-issue
      description: Creates an issue in GitHub
      script: GitHub|||GitHub-create-issue
      type: regular
      iscommand: true
      brand: GitHub
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      assignees: {}
      body: {}
      labels: {}
      milestone: {}
      title:
        simple: '"A whole new bug!"'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: a75cd271-3d10-46e1-8d12-aa3b85211193
    type: condition
    task:
      id: a75cd271-3d10-46e1-8d12-aa3b85211193
      version: -1
      name: Verify Results - create
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
      - "8"
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${GitHub.Issue.Title}
            iscontext: true
          right:
            value:
              simple: '"A whole new bug!"'
      - - operator: isEqualString
          left:
            value:
              simple: ${GitHub.Issue.Repository}
            iscontext: true
          right:
            value:
              simple: https://api.github.com/repos/roysagi/Git-Integration
      - - operator: isEqualString
          left:
            value:
              simple: ${GitHub.Issue.State}
            iscontext: true
          right:
            value:
              simple: open
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 692164c7-3699-4e4c-877d-b1c177f88160
    type: regular
    task:
      id: 692164c7-3699-4e4c-877d-b1c177f88160
      version: -1
      name: GitHub-update-issue
      description: Updates the parameters of a given issue
      script: GitHub|||GitHub-update-issue
      type: regular
      iscommand: true
      brand: GitHub
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      assignees: {}
      body:
        simple: '"new information"'
      issue_number:
        simple: ${GitHub.Issue.ID}
      labels: {}
      milestone: {}
      state: {}
      title: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 4021c091-ce45-4c3e-8906-1ff7439d566e
    type: condition
    task:
      id: 4021c091-ce45-4c3e-8906-1ff7439d566e
      version: -1
      name: Verify Results - update
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${GitHub.Issue.Repository}
            iscontext: true
          right:
            value:
              simple: https://api.github.com/repos/roysagi/Git-Integration
      - - operator: isEqualString
          left:
            value:
              simple: ${GitHub.Issue.Body}
            iscontext: true
          right:
            value:
              simple: '"new information"'
    view: |-
      {
        "position": {
          "x": 450,
          "y": 970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: ebb8d599-cc4c-4f0f-823f-6c78e66d7381
    type: condition
    task:
      id: ebb8d599-cc4c-4f0f-823f-6c78e66d7381
      version: -1
      name: Verify Results - search
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${GitHub.Issue.Repository}
            iscontext: true
          right:
            value:
              simple: https://api.github.com/repos/roysagi/Git-Integration
    view: |-
      {
        "position": {
          "x": 900,
          "y": 970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 0b3c7b5f-63ab-4fc3-8849-86a63641deeb
    type: regular
    task:
      id: 0b3c7b5f-63ab-4fc3-8849-86a63641deeb
      version: -1
      name: search-issues
      description: Searches issues matching a given query
      script: GitHub|||GitHub-search-issues
      type: regular
      iscommand: true
      brand: GitHub
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      query:
        simple: user:roysagi
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 900,
          "y": 780
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 99f9aaaa-1ebc-4a1b-81b7-416cb9f0dd6f
    type: regular
    task:
      id: 99f9aaaa-1ebc-4a1b-81b7-416cb9f0dd6f
      version: -1
      name: list-all-issues
      description: Lists all issues that the user can see
      script: GitHub|||GitHub-list-all-issues
      type: regular
      iscommand: true
      brand: GitHub
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      open_or_all: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 30,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 0dbd34ef-8c58-47c4-8435-553d24d9ba8a
    type: condition
    task:
      id: 0dbd34ef-8c58-47c4-8435-553d24d9ba8a
      version: -1
      name: Verify Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${GitHub.Issue.Repository}
            iscontext: true
          right:
            value:
              simple: https://api.github.com/repos/roysagi/Git-Integration
    view: |-
      {
        "position": {
          "x": 30,
          "y": 970
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: de248d10-92ec-4d91-81a8-369644d381ec
    type: regular
    task:
      id: de248d10-92ec-4d91-81a8-369644d381ec
      version: -1
      name: close-issue
      description: closes an existing issue
      script: GitHub|||GitHub-close-issue
      type: regular
      iscommand: true
      brand: GitHub
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      issue_number:
        simple: ${GitHub.Issue.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: c27310b7-eec5-455e-8b69-42687ed05971
    type: regular
    task:
      id: c27310b7-eec5-455e-8b69-42687ed05971
      version: -1
      name: get-download-count
      description: Returns the total amount of downloads over all the releases of
        the repository
      script: GitHub|||GitHub-get-download-count
      type: regular
      iscommand: true
      brand: GitHub
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 439e54ad-c530-42f3-8e86-7c561a7a5584
    type: condition
    task:
      id: 439e54ad-c530-42f3-8e86-7c561a7a5584
      version: -1
      name: Verify Results - download
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${GitHub.Release.URL}
            iscontext: true
          right:
            value:
              simple: https://api.github.com/repos/roysagi/Git-Integration/releases/17519182
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 1f339cb6-1c41-4a63-8c92-c873cb601b8e
    type: condition
    task:
      id: 1f339cb6-1c41-4a63-8c92-c873cb601b8e
      version: -1
      name: Verify Results - close
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${GitHub.Issue.State}
            iscontext: true
          right:
            value:
              simple: closed
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 88aae2b8-28ad-4eac-890e-8a8c2a0beac6
    type: regular
    task:
      id: 88aae2b8-28ad-4eac-890e-8a8c2a0beac6
      version: -1
      name: closeInvestigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id:
        simple: ${incident.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1585,
        "width": 1680,
        "x": 30,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
